# name: uncaught error in "done" callback
# command: ["qunit", "uncaught-error-callbacks-done.js"]

TAP version 13
ok 1 module1 > test1
1..1
# pass 1
# skip 0
# todo 0
# fail 0
Bail out! Error: No dice
  ---
  message: "Error: No dice"
  severity: failed
  stack: |
    Error: No dice
        at /qunit/test/cli/fixtures/uncaught-error-callbacks-done.js:2:9
        at qunit.js
        at internal
  ...

# exit code: 1
